#Application Configuration
server:
  port: 8091

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:client_DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      idle-timeout: 10000
  sql:
    init:
      platform: h2
      mode: always
      continue-on-error: true
      data-locations:
      - classpath*:data.sql      

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"